version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      jvm-dependencies:
        patterns: ["*"]
    open-pull-requests-limit: 3

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: gradle
    directory: /integration-fixtures/android
    schedule:
      interval: weekly
      day: monday
    groups:
      android-fixture:
        patterns:
          - "*"
